using System.CodeDom.Compiler;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace triaxis.CommandLine.SourceGenerator;

[Generator]
public class CommandTreeGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FqnFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .AddMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "triaxis.CommandLine.CommandAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => ExtractCommandModel(ctx, ct))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!);

        var collected = commandClasses.Collect();
        var compilationInfo = context.CompilationProvider.Select(static (c, _) =>
        {
            var hasUnsafeAccessor = c.GetTypeByMetadataName("System.Runtime.CompilerServices.UnsafeAccessorAttribute") is not null;
            var assemblyCommands = ExtractAssemblyCommands(c);
            return (AssemblyName: c.AssemblyName ?? "", HasUnsafeAccessor: hasUnsafeAccessor, AssemblyCommands: assemblyCommands);
        });
        var combined = collected.Combine(compilationInfo);

        context.RegisterSourceOutput(combined, static (spc, pair) =>
        {
            var (commands, info) = pair;
            if (commands.IsDefaultOrEmpty && info.AssemblyCommands.IsDefaultOrEmpty)
            {
                return;
            }

            var source = GenerateSource(commands, info.AssemblyCommands, info.AssemblyName, info.HasUnsafeAccessor);
            spc.AddSource("GeneratedCommandTree.g.cs", source);
        });

        // Entry-point generation pipeline: when the consuming project is an executable
        // with no user-written Main method, synthesize a Program.Main that bootstraps
        // the tool.
        var entryPointProps = context.AnalyzerConfigOptionsProvider.Select(static (opts, _) =>
        {
            opts.GlobalOptions.TryGetValue("build_property.TriaxisCommandLineConfigOverridePath", out var configPath);
            opts.GlobalOptions.TryGetValue("build_property.TriaxisCommandLineEnvironmentVariablePrefix", out var envPrefix);

            return (ConfigOverridePath: string.IsNullOrEmpty(configPath) ? (string?)null : configPath,
                    EnvironmentVariablePrefix: string.IsNullOrEmpty(envPrefix) ? (string?)null : envPrefix);
        });

        var entryPointModel = context.CompilationProvider.Combine(entryPointProps).Select(static (pair, ct) =>
        {
            var (compilation, props) = pair;
            if (compilation.Options.OutputKind != OutputKind.ConsoleApplication)
            {
                return null;
            }
            if (compilation.GetEntryPoint(ct) is not null)
            {
                return null;
            }

            // Tool package (UseDefaults) detection via a type unique to it.
            var hasToolPackage = compilation.GetTypeByMetadataName("triaxis.CommandLine.LoggingCommand") is not null;

            return new EntryPointModel(hasToolPackage,
                hasToolPackage ? props.ConfigOverridePath : null,
                hasToolPackage ? props.EnvironmentVariablePrefix : null);
        });

        context.RegisterSourceOutput(entryPointModel, static (spc, model) =>
        {
            if (model is null)
            {
                return;
            }
            spc.AddSource("GeneratedProgram.g.cs", GenerateEntryPointSource(model));
        });
    }

    private static string GenerateEntryPointSource(EntryPointModel model)
    {
        var sw = new StringWriter();
        var w = new IndentedTextWriter(sw);

        w.WriteLine("// <auto-generated/>");
        w.WriteLine("#nullable enable");
        w.WriteLine();
        w.WriteLine("using triaxis.CommandLine;");
        w.WriteLine();
        w.Block("namespace triaxis.CommandLine.Generated", () =>
        {
            w.WriteLine("[global::System.CodeDom.Compiler.GeneratedCode(\"triaxis.CommandLine.SourceGenerator\", \"1.0\")]");
            w.Block("internal static class GeneratedProgram", () =>
            {
                w.Block("internal static int Main(string[] args)", () =>
                {
                    if (model.HasToolPackage)
                    {
                        var parts = new List<string>();
                        if (model.ConfigOverridePath is not null)
                        {
                            parts.Add($"configOverridePath: {FormatString(model.ConfigOverridePath)}");
                        }
                        if (model.EnvironmentVariablePrefix is not null)
                        {
                            parts.Add($"environmentVariablePrefix: {FormatString(model.EnvironmentVariablePrefix)}");
                        }
                        parts.Add("commandsAssembly: typeof(GeneratedProgram).Assembly");
                        var argsList = string.Join(", ", parts);
                        w.WriteLine($"return global::triaxis.CommandLine.Tool.CreateBuilder(args).UseDefaults({argsList}).Run();");
                    }
                    else
                    {
                        w.WriteLine("return global::triaxis.CommandLine.Tool.CreateBuilder(args).AddCommandsFromAssembly(typeof(GeneratedProgram).Assembly).Run();");
                    }
                });
            });
        });

        w.Flush();
        return sw.ToString();
    }

    private static ImmutableArray<AssemblyCommandModel> ExtractAssemblyCommands(Compilation compilation)
    {
        var builder = ImmutableArray.CreateBuilder<AssemblyCommandModel>();
        foreach (var attr in compilation.Assembly.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != "triaxis.CommandLine.CommandAttribute")
            {
                continue;
            }

            var path = attr.ConstructorArguments
                .SelectMany(a => a.Kind == TypedConstantKind.Array
                    ? a.Values.Select(v => v.Value?.ToString())
                    : new[] { a.Value?.ToString() })
                .Where(s => s is not null)
                .ToArray();

            if (path.Length == 0)
            {
                continue;
            }

            string? description = null;
            string[]? aliases = null;
            foreach (var named in attr.NamedArguments)
            {
                switch (named.Key)
                {
                    case "Description":
                        description = named.Value.Value?.ToString();
                        break;
                    case "Aliases":
                        aliases = named.Value.Values.Select(v => v.Value?.ToString()!).ToArray();
                        break;
                }
            }

            builder.Add(new AssemblyCommandModel(path!, description, aliases));
        }

        return builder.ToImmutable();
    }

    private static CommandModel? ExtractCommandModel(GeneratorAttributeSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        var typeSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        var commandAttr = ctx.Attributes.FirstOrDefault(a =>
            a.AttributeClass?.ToDisplayString() == "triaxis.CommandLine.CommandAttribute");

        if (commandAttr is null)
        {
            return null;
        }

        var path = commandAttr.ConstructorArguments
            .SelectMany(a => a.Kind == TypedConstantKind.Array
                ? a.Values.Select(v => v.Value?.ToString())
                : new[] { a.Value?.ToString() })
            .Where(s => s is not null)
            .ToArray();

        string? description = null;
        string[]? aliases = null;

        foreach (var named in commandAttr.NamedArguments)
        {
            switch (named.Key)
            {
                case "Description":
                    description = named.Value.Value?.ToString();
                    break;
                case "Aliases":
                    aliases = named.Value.Values.Select(v => v.Value?.ToString()!).ToArray();
                    break;
            }
        }

        if (description is null)
        {
            var descAttr = typeSymbol.GetAttributes().FirstOrDefault(a =>
                a.AttributeClass?.ToDisplayString() == "System.ComponentModel.DescriptionAttribute");
            description = descAttr?.ConstructorArguments.FirstOrDefault().Value?.ToString();
        }

        var members = new List<MemberModel>();
        for (var current = typeSymbol; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() is "object" or "System.Object")
            {
                break;
            }
            CollectMembers(current, members, ct);
        }

        var executeMethod = DetectExecuteMethod(typeSymbol);
        var ctorParams = ExtractConstructorParameters(typeSymbol);

        return new CommandModel(
            typeSymbol.ToDisplayString(FqnFormat),
            path!,
            description,
            aliases,
            members.ToImmutableArray(),
            executeMethod,
            ctorParams);
    }

    private static ImmutableArray<ConstructorParameterModel> ExtractConstructorParameters(INamedTypeSymbol typeSymbol)
    {
        var ctors = typeSymbol.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .ToArray();

        // Prefer [ActivatorUtilitiesConstructor]-annotated constructor
        var chosen = ctors.FirstOrDefault(c =>
            c.GetAttributes().Any(a =>
                a.AttributeClass?.ToDisplayString() == "Microsoft.Extensions.DependencyInjection.ActivatorUtilitiesConstructorAttribute"));

        // Otherwise pick the constructor with the most parameters
        chosen ??= ctors
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();

        if (chosen is null || chosen.Parameters.Length == 0)
        {
            return ImmutableArray<ConstructorParameterModel>.Empty;
        }

        return chosen.Parameters
            .Select(p => new ConstructorParameterModel(p.Type.ToDisplayString(FqnFormat)))
            .ToImmutableArray();
    }

    private static ExecuteMethodModel DetectExecuteMethod(INamedTypeSymbol typeSymbol)
    {
        // Check ExecuteAsync(CancellationToken) first
        foreach (var m in typeSymbol.GetMembers("ExecuteAsync").OfType<IMethodSymbol>())
        {
            if (m.Parameters.Length == 1 &&
                m.Parameters[0].Type.ToDisplayString() == "System.Threading.CancellationToken")
            {
                var (kind, innerType) = AnalyzeReturnType(m.ReturnType);
                return new ExecuteMethodModel("ExecuteAsync", true, true,
                    m.ReturnType.ToDisplayString(FqnFormat),
                    kind, innerType);
            }
        }

        // Check ExecuteAsync()
        foreach (var m in typeSymbol.GetMembers("ExecuteAsync").OfType<IMethodSymbol>())
        {
            if (m.Parameters.Length == 0)
            {
                var (kind, innerType) = AnalyzeReturnType(m.ReturnType);
                return new ExecuteMethodModel("ExecuteAsync", true, false,
                    m.ReturnType.ToDisplayString(FqnFormat),
                    kind, innerType);
            }
        }

        // Check Execute()
        foreach (var m in typeSymbol.GetMembers("Execute").OfType<IMethodSymbol>())
        {
            if (m.Parameters.Length == 0)
            {
                var (kind, innerType) = AnalyzeReturnType(m.ReturnType);
                return new ExecuteMethodModel("Execute", false, false,
                    m.ReturnType.ToDisplayString(FqnFormat),
                    kind, innerType);
            }
        }

        return new ExecuteMethodModel("ExecuteAsync", true, false, "global::System.Threading.Tasks.Task", ReturnKind.Task, null);
    }

    private static (ReturnKind Kind, string? InnerTypeFqn) AnalyzeReturnType(ITypeSymbol returnType)
    {
        if (returnType.SpecialType == SpecialType.System_Void)
        {
            return (ReturnKind.Void, null);
        }

        if (returnType.SpecialType == SpecialType.System_Int32)
        {
            return (ReturnKind.Int, null);
        }

        var display = returnType.ToDisplayString();

        if (display == "System.Threading.Tasks.Task")
        {
            return (ReturnKind.Task, null);
        }

        if (returnType is INamedTypeSymbol { IsGenericType: true } nts)
        {
            var origDef = nts.OriginalDefinition.ToDisplayString();

            // Task<T>
            if (origDef == "System.Threading.Tasks.Task<TResult>")
            {
                var inner = nts.TypeArguments[0];

                if (inner.SpecialType == SpecialType.System_Int32)
                {
                    return (ReturnKind.TaskOfInt, null);
                }

                if (IsICommandInvocationResult(inner))
                {
                    return (ReturnKind.TaskOfICommandInvocationResult, null);
                }

                var elementType = GetIEnumerableElementType(inner);
                if (elementType is not null)
                {
                    return (ReturnKind.TaskOfIEnumerableOfT, elementType.ToDisplayString(FqnFormat));
                }

                return (ReturnKind.TaskOfT, inner.ToDisplayString(FqnFormat));
            }

            // IAsyncEnumerable<T>
            if (origDef == "System.Collections.Generic.IAsyncEnumerable<T>")
            {
                var elementFqn = nts.TypeArguments[0].ToDisplayString(FqnFormat);
                return (ReturnKind.IAsyncEnumerableOfT, elementFqn);
            }
        }

        // ICommandInvocationResult (non-generic, direct)
        if (IsICommandInvocationResult(returnType))
        {
            return (ReturnKind.ICommandInvocationResult, null);
        }

        // IEnumerable<T>
        var syncElement = GetIEnumerableElementType(returnType);
        if (syncElement is not null)
        {
            return (ReturnKind.IEnumerableOfT, syncElement.ToDisplayString(FqnFormat));
        }

        // Plain value
        return (ReturnKind.Value, returnType.ToDisplayString(FqnFormat));
    }

    private static bool IsICommandInvocationResult(ITypeSymbol type)
    {
        var display = type.ToDisplayString();
        if (display is "triaxis.CommandLine.ICommandInvocationResult"
            or "triaxis.CommandLine.ICommandInvocationResult?")
        {
            return true;
        }

        return type.AllInterfaces.Any(i =>
            i.ToDisplayString() == "triaxis.CommandLine.ICommandInvocationResult");
    }

    private static ITypeSymbol? GetIEnumerableElementType(ITypeSymbol type)
    {
        // Check direct implementation
        if (type is INamedTypeSymbol { IsGenericType: true } directNts)
        {
            var directOrig = directNts.OriginalDefinition.ToDisplayString();
            if (directOrig == "System.Collections.Generic.IEnumerable<T>")
            {
                var elem = directNts.TypeArguments[0];
                if (elem.SpecialType is not (SpecialType.System_Byte or SpecialType.System_Char))
                {
                    return elem;
                }
                return null;
            }
        }

        // Check interfaces
        foreach (var iface in type.AllInterfaces)
        {
            if (iface is { IsGenericType: true } ifaceNts)
            {
                var ifaceOrig = ifaceNts.OriginalDefinition.ToDisplayString();
                if (ifaceOrig == "System.Collections.Generic.IEnumerable<T>")
                {
                    var elem = ifaceNts.TypeArguments[0];
                    if (elem.SpecialType is not (SpecialType.System_Byte or SpecialType.System_Char))
                    {
                        return elem;
                    }
                }
            }
        }

        return null;
    }

    private static void CollectMembers(INamedTypeSymbol typeSymbol, List<MemberModel> members,
        System.Threading.CancellationToken ct, AccessPathSegment[]? accessPath = null)
    {
        foreach (var member in typeSymbol.GetMembers())
        {
            ct.ThrowIfCancellationRequested();

            if (member is not (IFieldSymbol or IPropertySymbol))
            {
                continue;
            }

            foreach (var attr in member.GetAttributes())
            {
                var attrName = attr.AttributeClass?.ToDisplayString();
                var memberType = member switch
                {
                    IFieldSymbol f => f.Type,
                    IPropertySymbol p => p.Type,
                    _ => null
                };

                if (memberType is null)
                {
                    continue;
                }

                if (memberType is INamedTypeSymbol nts &&
                    nts.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T &&
                    nts.TypeArguments.Length == 1)
                {
                    memberType = nts.TypeArguments[0];
                }

                var memberTypeFqn = memberType.ToDisplayString(FqnFormat);
                var isField = member is IFieldSymbol;
                var isPublic = member.DeclaredAccessibility == Accessibility.Public;
                var hasSetter = member is IFieldSymbol || (member is IPropertySymbol prop && prop.SetMethod is { IsInitOnly: false });
                var declaringTypeFqn = member.ContainingType.ToDisplayString(FqnFormat);
                var isMemberRequired = IsMemberRequired(member);

                switch (attrName)
                {
                    case "triaxis.CommandLine.ArgumentAttribute":
                    {
                        var name = GetNamedArgString(attr, "Name")
                            ?? GetConstructorArgString(attr, 0);
                        var desc = GetNamedArgString(attr, "Description")
                            ?? GetConstructorArgString(attr, 1);
                        var order = GetNamedArgDouble(attr, "Order");
                        var required = GetNamedArgBool(attr, "Required");
                        var requiredIsSet = attr.NamedArguments.Any(n => n.Key == "Required");
                        members.Add(new MemberModel(
                            MemberKind.Argument, member.Name, memberTypeFqn, isField, isPublic, hasSetter,
                            declaringTypeFqn, name, desc, null,
                            requiredIsSet ? required : null,
                            isMemberRequired,
                            order, null, accessPath ?? Array.Empty<AccessPathSegment>()));
                        break;
                    }
                    case "triaxis.CommandLine.OptionAttribute":
                    {
                        var name = GetNamedArgString(attr, "Name")
                            ?? GetConstructorArgString(attr, 0);
                        var desc = GetNamedArgString(attr, "Description");
                        var optAliases = GetConstructorArgStringArray(attr, 1)
                            ?? GetNamedArgStringArray(attr, "Aliases");
                        var order = GetNamedArgDouble(attr, "Order");
                        var required = GetNamedArgBool(attr, "Required");
                        var requiredIsSet = attr.NamedArguments.Any(n => n.Key == "Required");
                        members.Add(new MemberModel(
                            MemberKind.Option, member.Name, memberTypeFqn, isField, isPublic, hasSetter,
                            declaringTypeFqn, name, desc, optAliases,
                            requiredIsSet ? required : null,
                            isMemberRequired,
                            order, null, accessPath ?? Array.Empty<AccessPathSegment>()));
                        break;
                    }
                    case "triaxis.CommandLine.OptionsAttribute":
                    {
                        if (memberType is INamedTypeSymbol nestedType)
                        {
                            var segment = new AccessPathSegment(
                                member.Name, memberTypeFqn, isField, isPublic, hasSetter, declaringTypeFqn);
                            var newPath = (accessPath ?? Array.Empty<AccessPathSegment>()).Append(segment).ToArray();
                            CollectMembers(nestedType, members, ct, newPath);
                        }
                        break;
                    }
                    case "triaxis.CommandLine.InjectAttribute":
                    {
                        var injectType = GetNamedArgType(attr, "Type");
                        members.Add(new MemberModel(
                            MemberKind.Inject, member.Name, memberTypeFqn, isField, isPublic, hasSetter,
                            declaringTypeFqn, null, null, null, null, false,
                            0, injectType, accessPath ?? Array.Empty<AccessPathSegment>()));
                        break;
                    }
                }
            }
        }
    }

    private static bool IsMemberRequired(ISymbol member)
    {
        return member switch
        {
            IFieldSymbol f => f.IsRequired,
            IPropertySymbol p => p.IsRequired,
            _ => false,
        };
    }

    private static string? GetNamedArgString(AttributeData attr, string name)
    {
        var arg = attr.NamedArguments.FirstOrDefault(n => n.Key == name);
        return arg.Value.Value?.ToString();
    }

    private static bool GetNamedArgBool(AttributeData attr, string name)
    {
        var arg = attr.NamedArguments.FirstOrDefault(n => n.Key == name);
        return arg.Value.Value is true;
    }

    private static double GetNamedArgDouble(AttributeData attr, string name)
    {
        var arg = attr.NamedArguments.FirstOrDefault(n => n.Key == name);
        if (arg.Value.Value is double d)
        {
            return d;
        }
        if (arg.Value.Value is int i)
        {
            return i;
        }
        return 0;
    }

    private static string? GetNamedArgType(AttributeData attr, string name)
    {
        var arg = attr.NamedArguments.FirstOrDefault(n => n.Key == name);
        if (arg.Value.Value is INamedTypeSymbol nts)
        {
            return nts.ToDisplayString(FqnFormat);
        }
        return null;
    }

    private static string[]? GetNamedArgStringArray(AttributeData attr, string name)
    {
        var arg = attr.NamedArguments.FirstOrDefault(n => n.Key == name);
        if (arg.Value.Kind == TypedConstantKind.Array)
        {
            return arg.Value.Values.Select(v => v.Value?.ToString()!).ToArray();
        }
        return null;
    }

    private static string? GetConstructorArgString(AttributeData attr, int index)
    {
        if (index < attr.ConstructorArguments.Length)
        {
            var arg = attr.ConstructorArguments[index];
            return arg.Value?.ToString();
        }
        return null;
    }

    private static string[]? GetConstructorArgStringArray(AttributeData attr, int index)
    {
        if (index < attr.ConstructorArguments.Length)
        {
            var arg = attr.ConstructorArguments[index];
            if (arg.Kind == TypedConstantKind.Array)
            {
                return arg.Values.Select(v => v.Value?.ToString()!).ToArray();
            }
        }
        return null;
    }

    private static string GenerateSource(ImmutableArray<CommandModel> commands, ImmutableArray<AssemblyCommandModel> assemblyCommands, string assemblyName, bool hasUnsafeAccessor)
    {
        var sw = new StringWriter();
        var w = new IndentedTextWriter(sw);

        w.WriteLine("// <auto-generated/>");
        w.WriteLine("#nullable enable");
        w.WriteLine("#pragma warning disable CS8601 // Possible null reference assignment (UnsafeAccessor ref returns)");
        w.WriteLine();
        w.WriteLine("using System;");
        w.WriteLine("using System.CommandLine;");
        w.WriteLine("using System.CommandLine.Invocation;");
        w.WriteLine("using System.CommandLine.Parsing;");
        w.WriteLine("using System.Reflection;");
        w.WriteLine("using System.Runtime.CompilerServices;");
        w.WriteLine("using System.Threading;");
        w.WriteLine("using System.Threading.Tasks;");
        w.WriteLine("using Microsoft.Extensions.DependencyInjection;");
        w.WriteLine("using triaxis.CommandLine;");
        w.WriteLine("using triaxis.CommandLine.Invocation;");
        w.WriteLine();
        w.Block("namespace triaxis.CommandLine.Generated", () =>
        {
            w.Block("internal static class GeneratedCommandRegistration_", () =>
            {
                // Module initializer
                w.WriteLine("[ModuleInitializer]");
                w.Block("internal static void Register()", () =>
                {
                    w.WriteLine($"GeneratedCommandRegistration.Register({FormatString(assemblyName)}, AddGeneratedCommands);");
                });
                w.WriteLine();

                // Registration method
                w.Block("private static void AddGeneratedCommands(IToolBuilder builder)", () =>
                {
                    w.WriteLine("var getServiceProvider = builder.GetServiceProviderAccessor();");
                    w.WriteLine();
                    foreach (var cmd in commands)
                    {
                        var safeName = GetSafeName(cmd);
                        w.WriteLine($"{safeName}_Action.Register(builder, getServiceProvider);");
                    }

                    // Apply assembly-level [assembly: Command(...)] metadata to tree nodes
                    // (descriptions and aliases for intermediate/parent commands).
                    foreach (var asmCmd in assemblyCommands)
                    {
                        w.WriteLine();
                        w.WriteLine($"var __asmCmd_{string.Join("_", asmCmd.Path).Replace("-", "_")} = builder.GetCommand({FormatStringArray(asmCmd.Path)});");
                        var varName = $"__asmCmd_{string.Join("_", asmCmd.Path).Replace("-", "_")}";
                        if (asmCmd.Description is not null)
                        {
                            w.WriteLine($"{varName}.Description = {FormatString(asmCmd.Description)};");
                        }
                        if (asmCmd.Aliases is { Length: > 0 })
                        {
                            foreach (var alias in asmCmd.Aliases)
                            {
                                w.WriteLine($"{varName}.Aliases.Add({FormatString(alias)});");
                            }
                        }
                    }
                });
                w.WriteLine();
            });
            w.WriteLine();

            // Per-command action classes
            foreach (var cmd in commands)
            {
                GenerateCommandAction(w, cmd, hasUnsafeAccessor);
            }
        });

        w.Flush();
        return sw.ToString();
    }

    private static void GenerateCommandAction(IndentedTextWriter w, CommandModel cmd, bool hasUnsafeAccessor)
    {
        var safeName = GetSafeName(cmd);
        var args = GetArguments(cmd);
        var opts = GetOptions(cmd);
        var injects = cmd.Members.Where(m => m.Kind == MemberKind.Inject).ToArray();
        var nonPublicDirect = args.Concat(opts).Concat(injects).Where(m => !m.IsPublic && m.AccessPath.Length == 0).ToArray();
        var exec = cmd.ExecuteMethod;

        w.Block($"internal sealed class {safeName}_Action : AsynchronousCommandLineAction", () =>
        {
        // Fields
        w.WriteLine("private readonly Func<IServiceProvider> _getServiceProvider;");
        foreach (var arg in args)
        {
            w.WriteLine($"private readonly Argument<{arg.MemberTypeFqn}> _{GetMemberFieldName(arg)};");
        }
        foreach (var opt in opts)
        {
            w.WriteLine($"private readonly Option<{opt.MemberTypeFqn}> _{GetMemberFieldName(opt)};");
        }
        w.WriteLine();

        // Static Register method — creates action, wires up command
        w.Block("public static void Register(IToolBuilder builder, Func<IServiceProvider> getServiceProvider)", () =>
        {
            w.WriteLine($"var cmd = builder.GetCommand({FormatStringArray(cmd.Path)});");
            if (cmd.Description is not null)
            {
                w.WriteLine($"cmd.Description = {FormatString(cmd.Description)};");
            }
            if (cmd.Aliases is { Length: > 0 })
            {
                foreach (var alias in cmd.Aliases)
                {
                    w.WriteLine($"cmd.Aliases.Add({FormatString(alias)});");
                }
            }
            w.WriteLine("var action = new " + safeName + "_Action(getServiceProvider);");
            foreach (var arg in args)
            {
                w.WriteLine($"cmd.Arguments.Add(action._{GetMemberFieldName(arg)});");
            }
            foreach (var opt in opts)
            {
                w.WriteLine($"cmd.Options.Add(action._{GetMemberFieldName(opt)});");
            }
            w.WriteLine("cmd.Action = action;");
        });
        w.WriteLine();

        // Constructor
        w.Block($"private {safeName}_Action(Func<IServiceProvider> getServiceProvider)", () =>
        {
            w.WriteLine("_getServiceProvider = getServiceProvider;");
            foreach (var arg in args)
            {
                var fieldName = GetMemberFieldName(arg);
                w.WriteLine($"_{fieldName} = new Argument<{arg.MemberTypeFqn}>({FormatString(arg.Name ?? arg.MemberName)});");
                if (arg.Description is not null)
                {
                    w.WriteLine($"_{fieldName}.Description = {FormatString(arg.Description)};");
                }
                if (arg.Required == false)
                {
                    w.WriteLine($"_{fieldName}.Arity = new ArgumentArity(0, _{fieldName}.Arity.MaximumNumberOfValues);");
                }
                else if (arg.Required == true || arg.IsMemberRequired)
                {
                    w.WriteLine($"_{fieldName}.Arity = new ArgumentArity(1, _{fieldName}.Arity.MaximumNumberOfValues);");
                }
            }
            foreach (var opt in opts)
            {
                var fieldName = GetMemberFieldName(opt);
                var nameAndAliases = new List<string> { opt.Name ?? opt.MemberName };
                if (opt.Aliases is not null)
                {
                    nameAndAliases.AddRange(opt.Aliases);
                }
                var aliasesArr = nameAndAliases.Skip(1).ToArray();
                if (aliasesArr.Length > 0)
                {
                    w.WriteLine($"_{fieldName} = new Option<{opt.MemberTypeFqn}>({FormatString(nameAndAliases[0])}, {FormatStringArrayInline(aliasesArr)});");
                }
                else
                {
                    w.WriteLine($"_{fieldName} = new Option<{opt.MemberTypeFqn}>({FormatString(nameAndAliases[0])});");
                }
                if (opt.Description is not null)
                {
                    w.WriteLine($"_{fieldName}.Description = {FormatString(opt.Description)};");
                }
                if (opt.Required == true || opt.IsMemberRequired)
                {
                    w.WriteLine($"_{fieldName}.Required = true;");
                }
            }
        });
        w.WriteLine();

        // Accessors for direct members that need backing field access
        // (non-public members, or public read-only properties)
        // Skip required members — they are set in the object initializer.
        var memberAccessors = new Dictionary<string, Accessor>();
        foreach (var member in args.Concat(opts).Concat(injects).Where(m => m.AccessPath.Length == 0 && !m.IsMemberRequired))
        {
            var owner = member.DeclaringTypeFqn;
            memberAccessors[MemberKey(member)] = EmitAccessor(
                w, owner, member.MemberName, member.MemberTypeFqn,
                member.IsField, member.IsPublic, member.HasSetter,
                $"__access_{GetMemberFieldName(member)}", hasUnsafeAccessor);
        }

        // Accessors for [Options] path segments
        var pathAccessors = new Dictionary<string, Accessor>();
        foreach (var member in args.Concat(opts).Concat(injects))
        {
            foreach (var seg in member.AccessPath)
            {
                var key = seg.OwnerTypeFqn + "." + seg.MemberName;
                if (pathAccessors.ContainsKey(key))
                {
                    continue;
                }
                pathAccessors[key] = EmitAccessor(
                    w, seg.OwnerTypeFqn, seg.MemberName, seg.MemberTypeFqn,
                    seg.IsField, seg.IsPublic, seg.HasSetter,
                    $"__access_path_{seg.MemberName}", hasUnsafeAccessor);
            }
        }

        // Accessors for members on nested [Options] types that need backing field access
        foreach (var member in args.Concat(opts).Where(m => m.AccessPath.Length > 0))
        {
            var lastSeg = member.AccessPath[member.AccessPath.Length - 1];
            memberAccessors[MemberKey(member)] = EmitAccessor(
                w, lastSeg.MemberTypeFqn, member.MemberName, member.MemberTypeFqn,
                member.IsField, member.IsPublic, member.HasSetter,
                $"__access_{GetMemberFieldName(member)}", hasUnsafeAccessor);
        }

        // InvokeAsync
        w.Block("public override async Task<int> InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)", () =>
        {
            w.WriteLine("var provider = _getServiceProvider();");
            w.WriteLine($"var context = new InvocationContext(provider, parseResult, cancellationToken, typeof({cmd.TypeName}));");
            w.WriteLine();
            w.WriteLine("await provider.GetRequiredService<ICommandExecutor>().ExecuteAsync(context, async () =>");
            w.Block(() =>
            {
                // Identify required direct members that must go in the object initializer
                var requiredDirectArgs = args.Where(m => m.IsMemberRequired && m.AccessPath.Length == 0).ToArray();
                var requiredDirectOpts = opts.Where(m => m.IsMemberRequired && m.AccessPath.Length == 0).ToArray();
                var requiredDirectInjects = injects.Where(m => m.IsMemberRequired).ToArray();

                // Pre-bind required argument/option values before instance creation
                foreach (var arg in requiredDirectArgs)
                {
                    var fieldName = GetMemberFieldName(arg);
                    w.WriteLine($"var _bound_{fieldName} = parseResult.GetValue(_{fieldName});");
                }
                foreach (var opt in requiredDirectOpts)
                {
                    var fieldName = GetMemberFieldName(opt);
                    w.WriteLine($"var _bound_{fieldName} = parseResult.GetValue(_{fieldName});");
                }
                if (requiredDirectArgs.Length > 0 || requiredDirectOpts.Length > 0)
                {
                    w.WriteLine();
                }

                // Create instance — required members go in the object initializer
                var hasRequired = requiredDirectArgs.Length > 0 || requiredDirectOpts.Length > 0 || requiredDirectInjects.Length > 0;

                var ctorExpr = cmd.ConstructorParameters.IsEmpty
                    ? $"new {cmd.TypeName}()"
                    : $"new {cmd.TypeName}({string.Join(", ", cmd.ConstructorParameters.Select(p => $"provider.GetRequiredService<{p.TypeFqn}>()"))})";

                if (hasRequired)
                {
                    // Drop trailing "()" when using object initializer syntax
                    var initExpr = cmd.ConstructorParameters.IsEmpty
                        ? $"new {cmd.TypeName}"
                        : ctorExpr;
                    w.WriteLine($"var instance = {initExpr}");
                    w.WriteLine("{");
                    w.Indent++;
                    foreach (var arg in requiredDirectArgs)
                    {
                        w.WriteLine($"{arg.MemberName} = _bound_{GetMemberFieldName(arg)},");
                    }
                    foreach (var opt in requiredDirectOpts)
                    {
                        w.WriteLine($"{opt.MemberName} = _bound_{GetMemberFieldName(opt)},");
                    }
                    foreach (var inject in requiredDirectInjects)
                    {
                        var serviceType = inject.InjectTypeFqn ?? inject.MemberTypeFqn;
                        w.WriteLine($"{inject.MemberName} = provider.GetRequiredService<{serviceType}>(),");
                    }
                    w.Indent--;
                    w.WriteLine("};");
                }
                else
                {
                    w.WriteLine($"var instance = {ctorExpr};");
                }
                w.WriteLine();

                // Direct [Inject] assignments (skip required members already set in initializer)
                foreach (var inject in injects.Where(i => !i.IsMemberRequired))
                {
                    var serviceType = inject.InjectTypeFqn ?? inject.MemberTypeFqn;
                    w.WriteLine(FormatWrite(memberAccessors[MemberKey(inject)], "instance", $"provider.GetRequiredService<{serviceType}>()") + ";");
                }

                // Eagerly resolve [Options] nested objects
                GenerateOptionsPathResolution(w, args, opts, pathAccessors);

                // Inline bind: arguments (skip required direct members already set in initializer)
                foreach (var arg in args.Where(a => !a.IsMemberRequired || a.AccessPath.Length != 0))
                {
                    var fieldName = GetMemberFieldName(arg);
                    w.Block($"if (parseResult.GetResult(_{fieldName}) is {{ }} {fieldName}_result && {fieldName}_result.Tokens.Any())", () =>
                    {
                        WriteMemberAssignment(w, arg, $"parseResult.GetValue(_{fieldName})", memberAccessors[MemberKey(arg)]);
                    });
                }

                // Inline bind: options (skip required direct members already set in initializer)
                foreach (var opt in opts.Where(o => !o.IsMemberRequired || o.AccessPath.Length != 0))
                {
                    var fieldName = GetMemberFieldName(opt);
                    w.Block($"if (parseResult.GetResult(_{fieldName}) is {{ }} {fieldName}_result && !{fieldName}_result.Implicit)", () =>
                    {
                        WriteMemberAssignment(w, opt, $"parseResult.GetValue(_{fieldName})", memberAccessors[MemberKey(opt)]);
                    });
                }

                if (args.Length > 0 || opts.Length > 0)
                {
                    w.WriteLine();
                }

                // Execute
                if (exec.AcceptsCancellationToken)
                {
                    GenerateExecuteCall(w, cmd, "context.GetCancellationToken()");
                }
                else
                {
                    w.WriteLine("var failFastRegistration = context.GetCancellationToken().Register(static () => Environment.FailFast(null));");
                    w.Block("try", () =>
                    {
                        GenerateExecuteCall(w, cmd, null);
                    });
                    w.Block("finally", () =>
                    {
                        w.WriteLine("failFastRegistration.Dispose();");
                    });
                }
            });
            w.WriteLine(");");
            w.WriteLine();
            w.WriteLine("return context.ExitCode;");
        });

        }); // end class block
        w.WriteLine();
    }

    /// <summary>
    /// Emits the minimal accessor declaration needed for a member/segment and returns an
    /// <see cref="Accessor"/> describing how to read/write it inline at call sites.
    /// </summary>
    private static Accessor EmitAccessor(IndentedTextWriter w, string ownerTypeFqn,
        string memberName, string memberTypeFqn,
        bool isField, bool isPublic, bool hasSetter,
        string identifier, bool hasUnsafeAccessor)
    {
        // Public settable — no accessor declaration needed, access directly.
        if (isPublic && (isField || hasSetter))
        {
            return new Accessor(AccessorKind.Direct, "", memberName, memberTypeFqn);
        }

        // Public read-only property — read directly via getter, no declaration needed.
        // Write still requires a backing-field accessor (emitted below).
        if (isPublic && !isField && !hasSetter)
        {
            // Public read-only properties are only used as path segments (read + init-if-null).
            // The init-if-null path is not reachable for a public read-only path segment in the
            // current resolution logic (which throws for public read-only); but to be safe, emit
            // a backing-field setter so writes work. For now, use Direct-read with no setter.
            // We handle the read-only case by emitting only a setter declaration.
            var backingFieldName = "<" + memberName + ">k__BackingField";
            if (hasUnsafeAccessor)
            {
                w.WriteLine($"[UnsafeAccessor(UnsafeAccessorKind.Field, Name = {FormatString(backingFieldName)})]");
                w.WriteLine($"private static extern ref {memberTypeFqn} {identifier}({ownerTypeFqn} instance);");
                w.WriteLine();
                return new Accessor(AccessorKind.UnsafeFieldRef, identifier, memberName, memberTypeFqn);
            }
            else
            {
                w.WriteLine($"private static readonly FieldInfo {identifier} = typeof({ownerTypeFqn}).GetField({FormatString(backingFieldName)}, BindingFlags.Instance | BindingFlags.NonPublic)!;");
                w.WriteLine();
                return new Accessor(AccessorKind.ReflectionField, identifier, memberName, memberTypeFqn);
            }
        }

        // Non-public read-only property — need get_ method (UA) or PropertyInfo (reflection).
        if (!isField && !hasSetter)
        {
            if (hasUnsafeAccessor)
            {
                w.WriteLine($"[UnsafeAccessor(UnsafeAccessorKind.Method, Name = {FormatString("get_" + memberName)})]");
                w.WriteLine($"private static extern {memberTypeFqn} {identifier}({ownerTypeFqn} instance);");
                w.WriteLine();
                return new Accessor(AccessorKind.UnsafeGetter, identifier, memberName, memberTypeFqn);
            }
            else
            {
                w.WriteLine($"private static readonly PropertyInfo {identifier} = typeof({ownerTypeFqn}).GetProperty({FormatString(memberName)}, BindingFlags.Instance | BindingFlags.NonPublic)!;");
                w.WriteLine();
                return new Accessor(AccessorKind.ReflectionProperty, identifier, memberName, memberTypeFqn);
            }
        }

        // Non-public field, or non-public/init-only property with backing field.
        {
            var backingFieldName = isField ? memberName : "<" + memberName + ">k__BackingField";
            if (hasUnsafeAccessor)
            {
                w.WriteLine($"[UnsafeAccessor(UnsafeAccessorKind.Field, Name = {FormatString(backingFieldName)})]");
                w.WriteLine($"private static extern ref {memberTypeFqn} {identifier}({ownerTypeFqn} instance);");
                w.WriteLine();
                return new Accessor(AccessorKind.UnsafeFieldRef, identifier, memberName, memberTypeFqn);
            }
            else
            {
                w.WriteLine($"private static readonly FieldInfo {identifier} = typeof({ownerTypeFqn}).GetField({FormatString(backingFieldName)}, BindingFlags.Instance | BindingFlags.NonPublic)!;");
                w.WriteLine();
                return new Accessor(AccessorKind.ReflectionField, identifier, memberName, memberTypeFqn);
            }
        }
    }

    private static string FormatRead(Accessor a, string target) => a.Kind switch
    {
        AccessorKind.Direct => $"{target}.{a.MemberName}",
        AccessorKind.UnsafeFieldRef => $"{a.Identifier}({target})",
        AccessorKind.UnsafeGetter => $"{a.Identifier}({target})",
        AccessorKind.ReflectionField => $"({a.MemberTypeFqn}){a.Identifier}.GetValue({target})!",
        AccessorKind.ReflectionProperty => $"({a.MemberTypeFqn}){a.Identifier}.GetValue({target})!",
        _ => throw new InvalidOperationException(),
    };

    private static string FormatWrite(Accessor a, string target, string valueExpr) => a.Kind switch
    {
        AccessorKind.Direct => $"{target}.{a.MemberName} = {valueExpr}",
        AccessorKind.UnsafeFieldRef => $"{a.Identifier}({target}) = {valueExpr}",
        AccessorKind.ReflectionField => $"{a.Identifier}.SetValue({target}, {valueExpr})",
        _ => throw new InvalidOperationException($"Cannot write to accessor of kind {a.Kind}"),
    };

    private static string MemberKey(MemberModel m) =>
        string.Join(".", m.AccessPath.Select(s => s.MemberName).Append(m.MemberName));

    private static void GenerateExecuteCall(IndentedTextWriter w, CommandModel cmd, string? cancellationTokenArg)
    {
        var exec = cmd.ExecuteMethod;
        var callArgs = cancellationTokenArg is not null ? cancellationTokenArg : "";
        var call = $"instance.{exec.MethodName}({callArgs})";

        switch (exec.ReturnKind)
        {
            case ReturnKind.Void:
                w.WriteLine($"{call};");
                break;

            case ReturnKind.Task:
                w.WriteLine($"await {call};");
                break;

            case ReturnKind.Int:
                w.WriteLine($"context.ExitCode = {call};");
                break;

            case ReturnKind.TaskOfInt:
                w.WriteLine($"context.ExitCode = await {call};");
                break;

            case ReturnKind.TaskOfICommandInvocationResult:
                w.WriteLine($"context.InvocationResult = await {call};");
                break;

            case ReturnKind.ICommandInvocationResult:
                w.WriteLine($"context.InvocationResult = {call};");
                break;

            case ReturnKind.TaskOfIEnumerableOfT:
                w.WriteLine($"context.InvocationResult = new AsyncIEnumerableCommandInvocationResult<{exec.InnerTypeFqn}>({call});");
                break;

            case ReturnKind.TaskOfT:
                w.WriteLine($"context.InvocationResult = new AsyncValueCommandInvocationResult<{exec.InnerTypeFqn}>({call});");
                break;

            case ReturnKind.IAsyncEnumerableOfT:
                w.WriteLine($"context.InvocationResult = new AsyncEnumerableCommandInvocationResult<{exec.InnerTypeFqn}>({call});");
                break;

            case ReturnKind.IEnumerableOfT:
                w.WriteLine($"context.InvocationResult = new EnumerableCommandInvocationResult<{exec.InnerTypeFqn}>({call});");
                break;

            case ReturnKind.Value:
                w.WriteLine($"context.InvocationResult = new ValueCommandInvocationResult<{exec.InnerTypeFqn}>({call});");
                break;
        }
    }

    private static void WriteMemberAssignment(IndentedTextWriter w, MemberModel member, string valueExpr, Accessor accessor)
    {
        // For members with an access path, the path variable is resolved eagerly
        // in GenerateOptionsPathResolution and named __opts_{segment}
        var target = member.AccessPath.Length == 0
            ? "instance"
            : "__opts_" + string.Join("_", member.AccessPath.Select(s => s.MemberName));

        w.WriteLine(FormatWrite(accessor, target, valueExpr) + ";");
    }

    /// <summary>
    /// Generates eager resolution of all [Options] path prefixes used by arguments/options.
    /// Called once after instance creation, before any binding.
    /// </summary>
    private static void GenerateOptionsPathResolution(IndentedTextWriter w, MemberModel[] args, MemberModel[] opts, Dictionary<string, Accessor> pathAccessors)
    {
        var resolved = new HashSet<string>();
        foreach (var member in args.Concat(opts))
        {
            for (var depth = 1; depth <= member.AccessPath.Length; depth++)
            {
                var prefix = member.AccessPath.Take(depth).ToArray();
                var key = string.Join("_", prefix.Select(s => s.MemberName));
                if (!resolved.Add(key))
                {
                    continue;
                }

                var seg = prefix[depth - 1];
                var varName = $"__opts_{key}";
                var parentVar = depth == 1
                    ? "instance"
                    : "__opts_" + string.Join("_", prefix.Take(depth - 1).Select(s => s.MemberName));

                var accessor = pathAccessors[seg.OwnerTypeFqn + "." + seg.MemberName];
                var createExpr = $"Activator.CreateInstance<{seg.MemberTypeFqn}>()";
                var readExpr = FormatRead(accessor, parentVar);

                if (seg.IsField || seg.HasSetter)
                {
                    // Settable: read, create-if-null, assign back
                    if (accessor.Kind == AccessorKind.Direct)
                    {
                        w.WriteLine($"var {varName} = {readExpr} ?? ({FormatWrite(accessor, parentVar, createExpr)});");
                    }
                    else
                    {
                        w.WriteLine($"var {varName} = {readExpr};");
                        w.Block($"if ({varName} is null)", () =>
                        {
                            w.WriteLine($"{FormatWrite(accessor, parentVar, varName + " = " + createExpr)};");
                        });
                    }
                }
                else
                {
                    // Read-only: expect pre-initialized
                    w.WriteLine($"var {varName} = {readExpr} ?? throw new InvalidOperationException(\"[Options] property '{seg.MemberName}' returned null but has no setter\");");
                }
            }
        }
    }

    private static MemberModel[] GetArguments(CommandModel cmd) =>
        cmd.Members.Where(m => m.Kind == MemberKind.Argument).OrderBy(m => m.Order).ThenBy(m => m.Name).ToArray();

    private static MemberModel[] GetOptions(CommandModel cmd) =>
        cmd.Members.Where(m => m.Kind == MemberKind.Option).OrderBy(m => m.Order).ThenBy(m => m.Name).ToArray();

    private static string GetSafeName(CommandModel cmd)
    {
        return string.Join("_", cmd.Path).Replace("-", "_");
    }

    private static string GetMemberFieldName(MemberModel member)
    {
        if (member.AccessPath.Length > 0)
        {
            return string.Join("_", member.AccessPath.Select(s => s.MemberName)) + "_" + member.MemberName;
        }
        return member.MemberName;
    }

    private static string FormatString(string value)
    {
        return SyntaxFactory.Literal(value).ToFullString();
    }

    private static string FormatStringArray(string[] values)
    {
        if (values.Length == 0)
        {
            return "";
        }
        return string.Join(", ", values.Select(FormatString));
    }

    private static string FormatStringArrayInline(string[] values)
    {
        return "new[] { " + string.Join(", ", values.Select(FormatString)) + " }";
    }
}

enum MemberKind
{
    Argument,
    Option,
    Inject,
}

enum AccessorKind
{
    /// <summary>Public settable: access directly via <c>instance.Member</c>.</summary>
    Direct,
    /// <summary>[UnsafeAccessor] field ref return: <c>method(instance)</c> yields a ref.</summary>
    UnsafeFieldRef,
    /// <summary>[UnsafeAccessor] get_ method: <c>method(instance)</c> reads via property getter.</summary>
    UnsafeGetter,
    /// <summary>Cached <see cref="System.Reflection.FieldInfo"/> used for GetValue/SetValue.</summary>
    ReflectionField,
    /// <summary>Cached <see cref="System.Reflection.PropertyInfo"/> used for GetValue.</summary>
    ReflectionProperty,
}

record Accessor(AccessorKind Kind, string Identifier, string MemberName, string MemberTypeFqn);

enum ReturnKind
{
    Void,
    Task,
    Int,
    TaskOfInt,
    TaskOfICommandInvocationResult,
    TaskOfIEnumerableOfT,
    TaskOfT,
    IAsyncEnumerableOfT,
    IEnumerableOfT,
    ICommandInvocationResult,
    Value,
}

record ExecuteMethodModel(
    string MethodName,
    bool IsAsync,
    bool AcceptsCancellationToken,
    string ReturnTypeFqn,
    ReturnKind ReturnKind,
    string? InnerTypeFqn);

record CommandModel(
    string TypeName,
    string[] Path,
    string? Description,
    string[]? Aliases,
    ImmutableArray<MemberModel> Members,
    ExecuteMethodModel ExecuteMethod,
    ImmutableArray<ConstructorParameterModel> ConstructorParameters);

record AssemblyCommandModel(
    string[] Path,
    string? Description,
    string[]? Aliases);

record EntryPointModel(
    bool HasToolPackage,
    string? ConfigOverridePath,
    string? EnvironmentVariablePrefix);

record AccessPathSegment(
    string MemberName,
    string MemberTypeFqn,
    bool IsField,
    bool IsPublic,
    bool HasSetter,
    string OwnerTypeFqn);

record MemberModel(
    MemberKind Kind,
    string MemberName,
    string MemberTypeFqn,
    bool IsField,
    bool IsPublic,
    bool HasSetter,
    string DeclaringTypeFqn,
    string? Name,
    string? Description,
    string[]? Aliases,
    bool? Required,
    bool IsMemberRequired,
    double Order,
    string? InjectTypeFqn,
    AccessPathSegment[] AccessPath);

record ConstructorParameterModel(
    string TypeFqn);

static class IndentedTextWriterExtensions
{
    public static void Block(this IndentedTextWriter w, Action body)
    {
        w.WriteLine("{");
        w.Indent++;
        body();
        w.Indent--;
        w.WriteLine("}");
    }

    public static void Block(this IndentedTextWriter w, string header, Action body)
    {
        w.WriteLine(header);
        w.Block(body);
    }
}
